### ISSUE TITLE
Dockerfile: avdmanager does not work with OpenJDK 13, breaks build

### ISSUE THREAD

**Issue by lerela** [kivy/buildozer#1173]
### Versions

* Python: 3.8
* OS: Ubuntu 20.04
* Buildozer: master

### Description

Building an app using the container generated by the Dockerfile in master fails since #1140 since avdmanager does not support Java > 8 (see stackoverflow: [1](https://stackoverflow.com/questions/46402772/failed-to-install-android-sdk-java-lang-noclassdeffounderror-javax-xml-bind-a) [2](https://stackoverflow.com/questions/47150410/failed-to-run-sdkmanager-list-with-java-9), proposed fixes only work with Java < 11).

Replacing `openjdk-13-jdk` by `openjdk-8-jdk` in the Dockerfile fixes the issue.

### Logs

Build output follows:

```
# Run '/usr/bin/python3 -m pythonforandroid.toolchain create --dist_name=xx --bootstrap=sdl2 --requirements=sqlite3,openssl,python3,plyer,kivy,requests,certifi,setuptools,android,pycryptodome,humanize,urllib3,numpy,oscpy,chardet,idna --arch arm64-v8a --copy-libs --color=always --storage-dir="/home/user/hostcwd/.buildozer/android/platform/build-arm64-v8a" --ndk-api=24'
# Cwd /home/user/hostcwd/.buildozer/android/platform/python-for-android
/home/user/hostcwd/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py:84: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
[INFO]:    Will compile for the following archs: arm64-v8a
[INFO]:    Found Android API target in $ANDROIDAPI: 29
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/user/hostcwd/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 1260, in <module>
    main()
  File "/home/user/hostcwd/.buildozer/android/platform/python-for-android/pythonforandroid/entrypoints.py", line 18, in main
    ToolchainCL()
  File "/home/user/hostcwd/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 709, in __init__
    getattr(self, command)(args)
  File "/home/user/hostcwd/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 144, in wrapper_func
    ctx.prepare_build_environment(user_sdk_dir=self.sdk_dir,
  File "/home/user/hostcwd/.buildozer/android/platform/python-for-android/pythonforandroid/build.py", line 336, in prepare_build_environment
    apis = get_available_apis(self.sdk_dir)
  File "/home/user/hostcwd/.buildozer/android/platform/python-for-android/pythonforandroid/build.py", line 83, in get_available_apis
    targets = get_targets(sdk_dir)
  File "/home/user/hostcwd/.buildozer/android/platform/python-for-android/pythonforandroid/build.py", line 70, in get_targets
    targets = avdmanager("list", "target").stdout.decode("utf-8").split("\n")
  File "/home/user/.local/lib/python3.8/site-packages/sh.py", line 1549, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/home/user/.local/lib/python3.8/site-packages/sh.py", line 793, in __init__
    self.wait()
  File "/home/user/.local/lib/python3.8/site-packages/sh.py", line 849, in wait
    self.handle_command_exit_code(exit_code)
  File "/home/user/.local/lib/python3.8/site-packages/sh.py", line 877, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /home/lelio/Android/Sdk/tools/bin/avdmanager list target

  STDOUT:


  STDERR:
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.AvdManagerCli.run(AvdManagerCli.java:213)
	at com.android.sdklib.tool.AvdManagerCli.main(AvdManagerCli.java:200)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 5 more
```
