### ISSUE TITLE
Again: AttributeError: 'str' object has no attribute 'decode

### ISSUE THREAD

**Issue by alxd** [kivy/buildozer#1561]
I just did a pip install and had the same issue 

Versions
Python: 3.8
OS: Ubuntu 20.04.4 LTS on WSL Windows 10
Buildozer 1.5.0 - seems to be the latest: [Releases 9](https://github.com/kivy/buildozer/releases) 1.5.0 (2023-01-28)

buildozer android release

 Search for Git (git)
  -> found at /usr/bin/git
 Search for Cython (cython)
  -> found at /home/alex/.local/bin/cython
 Search for Java compiler (javac)
  -> found at /usr/lib/jvm/java-11-openjdk-amd64/bin/javac
 Search for Java keytool (keytool)
  -> found at /usr/lib/jvm/java-11-openjdk-amd64/bin/keytool
 Install platform
 Run ['git', 'config', '--get', 'remote.origin.url']
 Cwd /mnt/c/Python38/share/kivy-examples/camera/.buildozer/android/platform/python-for-android
https://github.com/kivy/python-for-android.git
 Run ['git', 'branch', '-vv']
 Cwd /mnt/c/Python38/share/kivy-examples/camera/.buildozer/android/platform/python-for-android
* master ee9c2570 [origin/master] Merge pull request 2740 from misl6/release-2023.01.28
 Run ['/usr/bin/python3', '-m', 'pip', 'install', '-q', '--user', 'appdirs', 'colorama>=0.3.3', 'jinja2', 'sh>=1.10; sys_platform!="nt"', 'pep517', 'toml', 'packaging']
 Cwd None
 Apache ANT found at /home/alex/.buildozer/android/platform/apache-ant-1.9.4
 Android SDK found at /home/alex/.buildozer/android/platform/android-sdk
 Recommended android's NDK version by p4a is: 25b
 Android NDK found at /home/alex/.buildozer/android/platform/android-ndk-r25b
    targets = avdmanager('list', 'target').stdout.decode('utf-8').split('\n')
AttributeError: 'str' object has no attribute 'stdout'
 Command failed: ['/usr/bin/python3', '-m', 'pythonforandroid.toolchain', 'create', '--dist_name=myapp', '--bootstrap=sdl2', '--requirements=python3,kivy', '--arch=arm64-v8a', '--arch=armeabi-v7a', '--copy-libs', '--color=always', '--storage-dir=/mnt/c/Python38/share/kivy-examples/camera/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a', '--ndk-api=21', '--ignore-setup-py', '--debug']
 ENVIRONMENT:
     SHELL = '/bin/bash'
     WSL_DISTRO_NAME = 'Ubuntu'
     NAME = 'NEW-BS2HP1L1NII'
     PWD = '/mnt/c/Python38/share/kivy-examples/camera'
     LOGNAME = 'alex'
     HOME = '/home/alex'
     LANG = 'C.UTF-8'
     WSL_INTEROP = '/run/WSL/8_interop'

Same previous bug: 
https://github.com/kivy/buildozer/issues/756

              Thanks for the bug report. Yes this is a bug recently introduced in https://github.com/kivy/python-for-android/pull/1475
Until this is fixed, you can edit `pythonforandroid/recipes/android/__init__.py` and remove `decode('utf-8')` part from the `self.ctx.bootstrap.name.decode('utf-8')` line

_Originally posted by @AndreMiras in https://github.com/kivy/buildozer/issues/756#issuecomment-443350792_

**Comment by misl6** [comment]
Fixed via https://github.com/kivy/python-for-android/pull/2746

We also have made an emergency release to target this issue: https://github.com/kivy/python-for-android/releases/tag/v2023.02.10

Please delete your `.buildozer` folder and try again.
