### ISSUE TITLE
Error compiling Cython file on Ubuntu 14.0.4 with python 2.7 and 3.4/5 

### ISSUE THREAD

**Issue by mmontielpz** [kivy/buildozer#536]
Hi I'm new with kivy and I want to build my app with buildozer to install the apk in my phone, but I can't build it, the console always throws me the same error with the cython file compiling, I tried with different versions of python but the problem persists.

# Python 2.7

``` 
# Check configuration tokens
# Ensure build layout
# Check configuration tokens
# Preparing build
# Check requirements for android
# Run 'dpkg --version'
# Cwd None
Programa de gestión de paquetes de Debian `dpkg' versión 1.17.5 (amd64).
Esto es software libre; consulte la Licencia Pública General de GNU versión 2 o
posterior para conocer las condiciones de copia. No hay NINGUNA garantía.
# Search for Git (git)
#  -> found at /usr/bin/git
# Search for Cython (cython)
#  -> found at /usr/local/bin/cython
# Search for Java compiler (javac)
#  -> found at /usr/lib/jvm/java-7-openjdk-amd64/bin/javac
# Search for Java keytool (keytool)
#  -> found at /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/keytool
# Install platform
# Run 'pip install -q --user "appdirs" "colorama>=0.3.3" "sh>=1.10" "jinja2" "six"'
# Cwd None
# Apache ANT found at /home/mike/.buildozer/android/platform/apache-ant-1.9.4
# Android SDK found at /home/mike/.buildozer/android/platform/android-sdk-20
# Android NDK found at /home/mike/.buildozer/android/platform/android-ndk-r9c
# Check application requirements
# Check garden requirements
# Compile platform
# Run '/usr/bin/python -m pythonforandroid.toolchain create --dist_name=myapp --bootstrap=sdl2 --requirements=hostpython2,kivy --arch armeabi-v7a --copy-libs --color=alwa
ys --storage-dir=/home/mike/kivy/games/GunMartians/.buildozer/android/platform/build'
# Cwd /home/mike/kivy/games/GunMartians/.buildozer/android/platform/python-for-android-master
[INFO]:    Will compile for the following archs: armeabi-v7a
[INFO]:    Found Android API target in $ANDROIDAPI
[INFO]:    Available Android APIs are (19)
[INFO]:    Requested API target 19 is available, continuing.
[INFO]:    Found NDK dir in $ANDROIDNDK
[INFO]:    Got NDK version from $ANDROIDNDKVER
[INFO]:    Using Google NDK r9c
[INFO]:    Found virtualenv at /usr/local/bin/virtualenv
[INFO]:    Found the following toolchain versions: ['4.6', '4.8', 'clang3.3']
[INFO]:    Picking the latest gcc toolchain, here 4.8
[WARNING]: Missing executable: autoconf is not installed
[WARNING]: Missing executable: automake is not installed
[INFO]:    No existing dists meet the given requirements!
[INFO]:    No dist exists that meets your requirements, so one will be built.
[INFO]:    Bootstrap requires recipes ['sdl2', ('python2', 'python3crystax')]
[INFO]:    Loaded recipe sdl2 (depends on [('python2', 'python3crystax'), 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf'], conflicts ['sdl', 'pygame', 'pygame_bootstrap_component
s'])
[INFO]:    Loaded recipe hostpython2 (depends on [], conflicts ['hostpython3'])
[INFO]:    Loaded recipe kivy (depends on ['pyjnius', ('sdl2', 'pygame'), ('python2', 'python3crystax')])
[INFO]:    Loaded recipe sdl2_image (depends on [])
[INFO]:    Loaded recipe sdl2_mixer (depends on [])
[INFO]:    Loaded recipe sdl2_ttf (depends on [])
[INFO]:    Loaded recipe pyjnius (depends on ['six', ('sdl2', 'sdl', 'genericndkbuild'), ('python2', 'python3crystax')])
[INFO]:    Loaded recipe six (depends on [('python2', 'python3crystax')])
[INFO]:    Found multiple valid recipe sets:
[INFO]:        ['six', 'sdl2', u'kivy', 'sdl2_ttf', u'hostpython2', 'sdl2_mixer', 'sdl2_image', 'pyjnius', 'python2']
[INFO]:        ['sdl2', 'six', 'sdl2_ttf', u'hostpython2', 'python3crystax', 'sdl2_mixer', 'sdl2_image', 'pyjnius', u'kivy']
[INFO]:    Using the first of these: ['six', 'sdl2', u'kivy', 'sdl2_ttf', u'hostpython2', 'sdl2_mixer', 'sdl2_image', 'pyjnius', 'python2']
[INFO]:    The selected bootstrap is sdl2
[INFO]:    # Creating dist with sdl2 bootstrap
[INFO]:    Dist will have name myapp and recipes (hostpython2, kivy)
[INFO]:    -> running cp -r /home/mike/kivy/games/GunMartians/.buildozer/android/platform/python-for-android-master/pythonforandroid/bootstrap...(and 116 more)
[INFO]:    -> directory context /home/mike/kivy/games/GunMartians/.buildozer/android/platform/build/build/bootstrap_builds/sdl2-python2
[INFO]:    <- directory context /home/mike/kivy/games/GunMartians/.buildozer/android/platform/python-for-android-master
[INFO]:    Recipe build order is [u'hostpython2', 'python2', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'sdl2', 'six', 'pyjnius', u'kivy']
[INFO]:    # Downloading recipes
[INFO]:    Downloading hostpython2
[INFO]:    -> running mkdir -p /home/mike/kivy/games/GunMartians/.buildozer/android/platform/build/packages/hostpython2
[INFO]:    -> directory context /home/mike/kivy/games/GunMartians/.buildozer/android/platform/build/packages/hostpython2
[INFO]:    -> running basename http://python.org/ftp/python/2.7.2/Python-2.7.2.tar.bz2
[INFO]:    hostpython2 download already cached, skipping
[INFO]:    <- directory context /home/mike/kivy/games/GunMartians/.buildozer/android/platform/python-for-android-master
[INFO]:    Downloading python2
[INFO]:    -> running mkdir -p /home/mike/kivy/games/GunMartians/.buildozer/android/platform/build/packages/python2
[INFO]:    -> directory context /home/mike/kivy/games/GunMartians/.buildozer/android/platform/build/packages/python2
[INFO]:    -> running basename http://python.org/ftp/python/2.7.2/Python-2.7.2.tar.bz2
[INFO]:    python2 download already cached, skipping
[INFO]:    <- directory context /home/mike/kivy/games/GunMartians/.buildozer/android/platform/python-for-android-master
[INFO]:    Downloading sdl2_image
[INFO]:    -> running mkdir -p /home/mike/kivy/games/GunMartians/.buildozer/android/platform/build/packages/sdl2_image
[INFO]:    -> directory context /home/mike/kivy/games/GunMartians/.buildozer/android/platform/build/packages/sdl2_image
[INFO]:    -> running basename https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.1.tar.gz
                                                                                                                                                   [INFO]:    sdl2_image d
ownload already cached, skipping
[INFO]:    <- directory context /home/mike/kivy/games/GunMartians/.buildozer/android/platform/python-for-android-master
[INFO]:    Downloading sdl2_mixer
[INFO]:    -> running mkdir -p /home/mike/kivy/games/GunMartians/.buildozer/android/platform/build/packages/sdl2_mixer
[INFO]:    -> directory context /home/mike/kivy/games/GunMartians/.buildozer/android/platform/build/packages/sdl2_mixer
[INFO]:    -> running basename https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.1.tar.gz
[INFO]:    sdl2_mixer download already cached, skipping
[INFO]:    <- directory context /home/mike/kivy/games/GunMartians/.buildozer/android/platform/python-for-android-master
[INFO]:    Downloading sdl2_ttf
[INFO]:    -> running mkdir -p /home/mike/kivy/games/GunMartians/.buildozer/android/platform/build/packages/sdl2_ttf
[INFO]:    -> directory context /home/mike/kivy/games/GunMartians/.buildozer/android/platform/build/packages/sdl2_ttf
[INFO]:    -> running basename https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-2.0.14.tar.gz
[INFO]:    sdl2_ttf download already cached, skipping
[INFO]:    <- directory context /home/mike/kivy/games/GunMartians/.buildozer/android/platform/python-for-android-master
[INFO]:    Downloading sdl2
[INFO]:    -> running mkdir -p /home/mike/kivy/games/GunMartians/.buildozer/android/platform/build/packages/sdl2
[INFO]:    -> directory context /home/mike/kivy/games/GunMartians/.buildozer/android/platform/build/packages/sdl2
[INFO]:    -> running basename https://www.libsdl.org/release/SDL2-2.0.4.tar.gz
                                                                                                                            [INFO]:    <- directory context /home/mike/kiv
y/games/GunMartians/.buildozer/android/platform/python-for-android-master
[INFO]:    Downloading six
[INFO]:    -> running mkdir -p /home/mike/kivy/games/GunMartians/.buildozer/android/platform/build/packages/six
[INFO]:    -> directory context /home/mike/kivy/games/GunMartians/.buildozer/android/platform/build/packages/six
[INFO]:    -> running basename https://pypi.python.org/packages/source/s/six/six-1.9.0.tar.gz
[INFO]:    six download already cached, skipping
[INFO]:    <- directory context /home/mike/kivy/games/GunMartians/.buildozer/android/platform/python-for-android-master
[INFO]:    Downloading pyjnius
[INFO]:    -> running mkdir -p /home/mike/kivy/games/GunMartians/.buildozer/android/platform/build/packages/pyjnius
[INFO]:    -> directory context /home/mike/kivy/games/GunMartians/.buildozer/android/platform/build/packages/pyjnius
[INFO]:    -> running basename https://github.com/kivy/pyjnius/archive/master.zip
[INFO]:    pyjnius download already cached, skipping
[INFO]:    <- directory context /home/mike/kivy/games/GunMartians/.buildozer/android/platform/python-for-android-master
[INFO]:    Downloading kivy
[INFO]:    -> running mkdir -p /home/mike/kivy/games/GunMartians/.buildozer/android/platform/build/packages/kivy
[INFO]:    -> directory context /home/mike/kivy/games/GunMartians/.buildozer/android/platform/build/packages/kivy
[INFO]:    -> running basename https://github.com/kivy/kivy/archive/1.10.0.zip
                                                                                                     [INFO]:    kivy download already cached, skipping
[INFO]:    <- directory context /home/mike/kivy/games/GunMartians/.buildozer/android/platform/python-for-android-master
[INFO]:    # Building all recipes for arch armeabi-v7a
[INFO]:    # Unpacking recipes
[INFO]:    Unpacking hostpython2 for armeabi-v7a
[INFO]:    -> running basename http://python.org/ftp/python/2.7.2/Python-2.7.2.tar.bz2
[INFO]:    -> directory context /home/mike/kivy/games/GunMartians/.buildozer/android/platform/build/build/other_builds/hostpython2/desktop
[INFO]:    hostpython2 is already unpacked, skipping
[INFO]:    <- directory context /home/mike/kivy/games/GunMartians/.buildozer/android/platform/python-for-android-master
[INFO]:    Unpacking python2 for armeabi-v7a
[INFO]:    -> running basename http://python.org/ftp/python/2.7.2/Python-2.7.2.tar.bz2
[INFO]:    -> directory context /home/mike/kivy/games/GunMartians/.buildozer/android/platform/build/build/other_builds/python2/armeabi-v7a
[INFO]:    python2 is already unpacked, skipping
[INFO]:    <- directory context /home/mike/kivy/games/GunMartians/.buildozer/android/platform/python-for-android-master
[INFO]:    Unpacking sdl2_image for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.1.tar.gz
                                                                              [INFO]:    -> directory context /home/mike/kivy/games/GunMartians/.buildozer/android/platfor
m/build/build/bootstrap_builds/sdl2-python2/jni
[INFO]:    sdl2_image is already unpacked, skipping
[INFO]:    <- directory context /home/mike/kivy/games/GunMartians/.buildozer/android/platform/python-for-android-master
[INFO]:    Unpacking sdl2_mixer for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.1.tar.gz
[INFO]:    -> directory context /home/mike/kivy/games/GunMartians/.buildozer/android/platform/build/build/bootstrap_builds/sdl2-python2/jni
[INFO]:    sdl2_mixer is already unpacked, skipping
[INFO]:    <- directory context /home/mike/kivy/games/GunMartians/.buildozer/android/platform/python-for-android-master
[INFO]:    Unpacking sdl2_ttf for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-2.0.14.tar.gz
[INFO]:    -> directory context /home/mike/kivy/games/GunMartians/.buildozer/android/platform/build/build/bootstrap_builds/sdl2-python2/jni
[INFO]:    sdl2_ttf is already unpacked, skipping
[INFO]:    <- directory context /home/mike/kivy/games/GunMartians/.buildozer/android/platform/python-for-android-master
[INFO]:    Unpacking sdl2 for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.org/release/SDL2-2.0.4.tar.gz
                                                       [INFO]:    -> directory context /home/mike/kivy/games/GunMartians/.buildozer/android/platform/build/build/bootstrap
_builds/sdl2-python2/jni
[INFO]:    sdl2 is already unpacked, skipping
[INFO]:    <- directory context /home/mike/kivy/games/GunMartians/.buildozer/android/platform/python-for-android-master
[INFO]:    Unpacking six for armeabi-v7a
[INFO]:    -> running basename https://pypi.python.org/packages/source/s/six/six-1.9.0.tar.gz
[INFO]:    -> directory context /home/mike/kivy/games/GunMartians/.buildozer/android/platform/build/build/other_builds/six-python2/armeabi-v7a
[INFO]:    six is already unpacked, skipping
[INFO]:    <- directory context /home/mike/kivy/games/GunMartians/.buildozer/android/platform/python-for-android-master
[INFO]:    Unpacking pyjnius for armeabi-v7a
[INFO]:    -> running basename https://github.com/kivy/pyjnius/archive/master.zip
[INFO]:    -> directory context /home/mike/kivy/games/GunMartians/.buildozer/android/platform/build/build/other_builds/pyjnius-python2-sdl2/armeabi-v7a
[INFO]:    pyjnius is already unpacked, skipping
[INFO]:    <- directory context /home/mike/kivy/games/GunMartians/.buildozer/android/platform/python-for-android-master
[INFO]:    Unpacking kivy for armeabi-v7a
[INFO]:    -> running basename https://github.com/kivy/kivy/archive/1.10.0.zip
                                [INFO]:    -> directory context /home/mike/kivy/games/GunMartians/.buildozer/android/platform/build/build/other_builds/kivy-python2-sdl2/a
rmeabi-v7a
[INFO]:    kivy is already unpacked, skipping
[INFO]:    <- directory context /home/mike/kivy/games/GunMartians/.buildozer/android/platform/python-for-android-master
[INFO]:    # Prebuilding recipes
[INFO]:    Prebuilding hostpython2 for armeabi-v7a
[INFO]:    -> running cp /home/mike/kivy/games/GunMartians/.buildozer/android/platform/python-for-android-master/pythonforandroid/recipes/host...(and 146 more)
[INFO]:    Prebuilding python2 for armeabi-v7a
[INFO]:    python2 has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for python2[armeabi-v7a]
[INFO]:    python2 already patched, skipping
[INFO]:    Prebuilding sdl2_image for armeabi-v7a
[INFO]:    sdl2_image has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for sdl2_image[armeabi-v7a]
[INFO]:    sdl2_image already patched, skipping
[INFO]:    Prebuilding sdl2_mixer for armeabi-v7a
[INFO]:    sdl2_mixer has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for sdl2_mixer[armeabi-v7a]
[INFO]:    sdl2_mixer already patched, skipping
[INFO]:    Prebuilding sdl2_ttf for armeabi-v7a
[INFO]:    sdl2_ttf has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding sdl2 for armeabi-v7a
[INFO]:    sdl2 has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for sdl2[armeabi-v7a]
[INFO]:    sdl2 already patched, skipping
[INFO]:    Prebuilding six for armeabi-v7a
[INFO]:    six has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding pyjnius for armeabi-v7a
[INFO]:    pyjnius has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for pyjnius[armeabi-v7a]
[INFO]:    pyjnius already patched, skipping
[INFO]:    Prebuilding kivy for armeabi-v7a
[INFO]:    kivy has no prebuild_armeabi_v7a, skipping
[INFO]:    # Building recipes
[INFO]:    Building hostpython2 for armeabi-v7a
[INFO]:    -> directory context /home/mike/kivy/games/GunMartians/.buildozer/android/platform/build/build/other_builds/hostpython2/desktop/hostpython2
[INFO]:    hostpython already exists, skipping build
[INFO]:    <- directory context /home/mike/kivy/games/GunMartians/.buildozer/android/platform/python-for-android-master
[INFO]:    Building python2 for armeabi-v7a
[INFO]:    Copying hostpython binary to targetpython folder
[INFO]:    -> running cp /home/mike/kivy/games/GunMartians/.buildozer/android/platform/build/build/other_builds/hostpython2/desktop/hostpython...(and 124 more)
[INFO]:    Building sdl2_image for armeabi-v7a
[INFO]:    Building sdl2_mixer for armeabi-v7a
[INFO]:    Building sdl2_ttf for armeabi-v7a
[INFO]:    Building sdl2 for armeabi-v7a
[INFO]:    -> directory context /home/mike/kivy/games/GunMartians/.buildozer/android/platform/build/build/bootstrap_builds/sdl2-python2/jni
[INFO]:    -> running ndk-build V=1
                                                                                                                             [INFO]:    <- directory context /home/mike/ki
vy/games/GunMartians/.buildozer/android/platform/python-for-android-master
[INFO]:    Building six for armeabi-v7a
[INFO]:    Python package already exists in site-packages
[INFO]:    six said it is already built, skipping
[INFO]:    Building pyjnius for armeabi-v7a
[INFO]:    Python package already exists in site-packages
[INFO]:    pyjnius said it is already built, skipping
[INFO]:    Building kivy for armeabi-v7a
[INFO]:    kivy apparently isn't already in site-packages
[INFO]:    Cythonizing anything necessary in kivy
[INFO]:    -> directory context /home/mike/kivy/games/GunMartians/.buildozer/android/platform/build/build/other_builds/kivy-python2-sdl2/armeabi-v7a/kivy
[INFO]:    -> running python.host -c import sys; print(sys.path)
[INFO]:    Trying first build of kivy to get cython files: this is expected to fail
[INFO]:    -> running python.host setup.py build_ext -v
('cwd is', '/home/mike/kivy/games/GunMartians/.buildozer/android/platform/build/build/other_builds/kivy-python2-sdl2/armeabi-v7a/kivy')
           working: building 'kivy.core.text._text_sdl2' extension                                                                                         Exception in th
read background thread for pid 24652:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 1540, in wrap
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 2459, in background_thread
    handle_exit_code(exit_code)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 2157, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
ErrorReturnCode_1:

  RAN: /home/mike/kivy/games/GunMartians/.buildozer/android/platform/build/build/python-installs/myapp/bin/python.host setup.py build_ext -v

  STDOUT:
Using distutils
Environ change use_sdl2 -> True

Cython check avoided.
Using this graphics system: OpenGL ES 2
WARNING: A problem occurred while running pkg-config --libs --cflags sdl2 SDL2_ttf SDL2_image SDL2_mixer (code 1)

Package sdl2 was not found in the pkg-config search path.
Perhaps you should add the directory containing `sdl2.pc'
to the PKG_CONFIG_PATH environment variable
No package 'sdl2' found
Package SDL2_ttf was not found in the pkg-config search path.
Perhaps you should add the directory containing `SDL2_ttf.pc'
to the PKG_CONFIG_PATH environment variable
No package 'SDL2_ttf' found
Package SDL2_image was not found in the pkg-config search path.
Perhaps you should add the directory containing `SDL2_image.pc'
to the PKG_CONFIG_PATH environment variable
No package 'SDL2_image' found
Package SDL2_mixer was not found in the pkg-config search path.
Perhaps you should add the directory containing `SDL2_mixer.pc'
to the PKG_CONFIG_PATH environment variable
No package 'SDL2_mixer' found


SDL2: found SDL header at /home/mike/kivy/games/GunMartians/.buildozer/android/platform/build/build/bootstrap_builds/sdl2-python2/jni/SDL/include/SDL.h
SDL2: found SDL_mixer header at /home/mike/kivy/games/GunMartians/.buildozer/android/platform/build/build/bootstrap_builds/sdl2-python2/jni/SDL2_mixer/SDL_mixer.h
SDL2: found SDL_ttf header at /home/mike/kivy/games/GunMartians/.buildozer/android/platform/build/build/bootstrap_builds/sdl2-python2/jni/SDL2_ttf/SDL_ttf.h
SDL2: found SDL_image header at /home/mike/kivy/games/GunMartians/.buildozer/android/platform/build/build/bootstrap_builds/sdl2-python2/jni/SDL2_image/SDL_image.h
fatal: Not a git repository (or any of the parent directories): .git
 /home/mike/kivy/games/GunMartians/.buildozer/android/platform/build/build/python-installs/myapp/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution op
tion: 'setup_requires'
   warnings.warn(msg)
 /home/mike/kivy/games/GunMartians/.buildozer/android/platform/build/build/python-installs/myapp/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution op
tion: 'dependency_links'
   warnings.warn(msg)
 /home/mike/kivy/games/GunMartians/.buildozer/android/platform/build/build/python-installs/myapp/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution op
tion: 'install_requires'
   warnings.warn(msg)
running build_ext
Build configuration is:
 * use_rpi = 0
 * use_mali = 0
 * use_egl = 0
 * use_opengl_es2 = 1
 * use_opengl_mock = 0
 * use_sdl2 = 1
 * use_ios = 0
 * use_mesagl = 0
 * use_x11 = 0
 * use_gstreamer = 0
 * use_avfoundation = 0
 * use_osx_frameworks = 0
 * debug_gl = 0
 * debug = False
Detected compiler is unix
building 'kivy.core.text._text_sdl2' extension
/usr/bin/ccache arm-linux-androideabi-gcc -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/mike/.buildozer/android/platform/android-ndk-r9c/platforms/android-19/a
rch-arm -DNDEBUG -g -O3 -Wall -Wstrict-prototypes -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/mike/.buildozer/android/platform/android-ndk-r9c/platforms/andr
oid-19/arch-arm -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -mthumb -fPIC -Ikivy/include -I/home/mike/kivy/games/GunMartians/.buildozer/android/platform/build/build/boots
trap_builds/sdl2-python2/jni/SDL/include -I/home/mike/kivy/games/GunMartians/.buildozer/android/platform/build/build/bootstrap_builds/sdl2-python2/jni/SDL2_image -I/home/
mike/kivy/games/GunMartians/.buildozer/android/platform/build/build/bootstrap_builds/sdl2-python2/jni/SDL2_mixer -I/home/mike/kivy/games/GunMartians/.buildozer/android/pl
atform/build/build/bootstrap_builds/sdl2-python2/jni/SDL2_ttf -I/home/mike/kivy/games/GunMartians/.buildozer/android/platform/build/build/python-installs/myapp/include/py
thon2.7 -c kivy/core/text/_text_sdl2.c -o build/temp.linux-x86_64-2.7/kivy/core/text/_text_sdl2.o
arm-linux-androideabi-gcc: error: kivy/core/text/_text_sdl2.c: No such file or directory
arm-linux-androideabi-gcc: fatal error: no input files
compilation terminated.
 error: command '/usr/bin/ccache' failed with exit status 1


  STDERR:


                                                                                                                                       [INFO]:    kivy first build failed
(as expected)
[INFO]:    Running cython where appropriate
[INFO]:    Cythonize kivy/_clock.pyx
[INFO]:    -> running cython ./kivy/_clock.pyx
[INFO]:    Cythonize kivy/_event.pyx
[INFO]:    -> running cython ./kivy/_event.pyx
[INFO]:    Cythonize kivy/properties.pyx
[INFO]:    -> running cython ./kivy/properties.pyx
[INFO]:    Cythonize kivy/weakproxy.pyx
[INFO]:    -> running cython ./kivy/weakproxy.pyx
[INFO]:    Cythonize kivy/lib/gstplayer/_gstplayer.pyx
[INFO]:    -> running cython ./kivy/lib/gstplayer/_gstplayer.pyx
[INFO]:    Cythonize kivy/lib/vidcore_lite/egl.pyx
[INFO]:    -> running cython ./kivy/lib/vidcore_lite/egl.pyx
()
           working: kivy/lib/vidcore_lite/egl.pyx:619:17: cimported module has no attribuException in thread background thread for pid 24711:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 1540, in wrap
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 2459, in background_thread
    handle_exit_code(exit_code)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 2157, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
ErrorReturnCode_1:

  RAN: /usr/local/bin/cython ./kivy/lib/vidcore_lite/egl.pyx

  STDOUT:

Error compiling Cython file:
------------------------------------------------------------
...
    cdef:
        bcm.DISPMANX_DISPLAY_HANDLE_T disp
        bcm.DisplayHandle D
    disp = bcm.vc_dispmanx_display_open( device )
    if disp == 0:
        raise bcm.BCMDisplayException("Couldn't open handle to display")
                ^
------------------------------------------------------------

kivy/lib/vidcore_lite/egl.pyx:608:17: cimported module has no attribute 'BCMDisplayException'

Error compiling Cython file:
------------------------------------------------------------
...
    cdef:
        bcm.DISPMANX_UPDATE_HANDLE_T hdl
        bcm.UpdateHandle U
    hdl = bcm.vc_dispmanx_update_start( priority )
    if hdl == 0:
        raise bcm.BCMDisplayException("Couldn't open handle to update-start")
                ^
------------------------------------------------------------

kivy/lib/vidcore_lite/egl.pyx:619:17: cimported module has no attribute 'BCMDisplayException'


  STDERR:


Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/mike/kivy/games/GunMartians/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 905, in <module>
    main()
  File "/home/mike/kivy/games/GunMartians/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 902, in main
    ToolchainCL()
  File "/home/mike/kivy/games/GunMartians/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 508, in __init__
    getattr(self, args.subparser_name.replace('-', '_'))(args)
  File "/home/mike/kivy/games/GunMartians/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 147, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/home/mike/kivy/games/GunMartians/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 190, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx)
  File "pythonforandroid/build.py", line 565, in build_recipes
  File "pythonforandroid/recipe.py", line 975, in build_arch
  File "pythonforandroid/recipe.py", line 1010, in build_cython_components
  File "/home/mike/kivy/games/GunMartians/.buildozer/android/platform/python-for-android-master/pythonforandroid/recipes/kivy/__init__.py", line 18, in cythonize_build
    super(KivyRecipe, self).cythonize_build(env, build_dir=build_dir)
  File "pythonforandroid/recipe.py", line 1055, in cythonize_build
  File "pythonforandroid/recipe.py", line 1046, in cythonize_file
  File "pythonforandroid/logger.py", line 175, in shprint
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 863, in next
    self.wait()
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1:

  RAN: /usr/local/bin/cython ./kivy/lib/vidcore_lite/egl.pyx

  STDOUT:

Error compiling Cython file:
------------------------------------------------------------
...
    cdef:
        bcm.DISPMANX_DISPLAY_HANDLE_T disp
        bcm.DisplayHandle D
    disp = bcm.vc_dispmanx_display_open( device )
    if disp == 0:
        raise bcm.BCMDisplayException("Couldn't open handle to display")
                ^
------------------------------------------------------------

kivy/lib/vidcore_lite/egl.pyx:608:17: cimported module has no attribute 'BCMDisplayException'

Error compiling Cython file:
------------------------------------------------------------
...
    cdef:
        bcm.DISPMANX_UPDATE_HANDLE_T hdl
        bcm.UpdateHandle U
    hdl = bcm.vc_dispmanx_update_start( priority )
    if hdl == 0:
        raise bcm.BCMDisplayException("Couldn't open handle to update-start")
                ^
------------------------------------------------------------

kivy/lib/vidcore_lite/egl.pyx:619:17: cimported module has no attribute 'BCMDisplayException'


  STDERR:

# Command failed: /usr/bin/python -m pythonforandroid.toolchain create --dist_name=myapp --bootstrap=sdl2 --requirements=hostpython2,kivy --arch armeabi-v7a --copy-libs --color=always --storage-dir=/home/mike/kivy/games/GunMartians/.buildozer/android/platform/build
#
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2
```

I tried googling and found solutions which suggested reinstalling kivy, cython or buildozer and reconfigurate the .spec file to set the requirements, but none of them worked.

I'd appreciate any help that you may offer.
Thanks!

**Comment by lysuhin** [comment]
+1, having the same issue.
Trying to build [opencv-example](https://github.com/kivy/buildozer/files/1191204/main.py.zip).
Log with level 2 is [here](https://github.com/kivy/buildozer/files/1191206/log.txt)

**Comment by Kosti1** [comment]
Same thing, I really need to get this app built

**Comment by inclement** [comment]
Apparently this is a problem with cython 0.26. Does it work with 0.25?

**Comment by mmontielpz** [comment]
You are right inclement, the problem is the version of Cython 0.26 that is not compatible, I just review the [documentation](https://kivy.org/docs/installation/installation-linux.html#using-software-packages) and specify which versions are compliant, pip installs the latest version of Cyton, so you need to specify that version:

```
pip install cython == 0.25
```

Thank you!

**Comment by Zen-CODE** [comment]
Solved it for me too :-)

**Comment by Richzendy** [comment]
Doesn't work with Cython 0.27.1, solved using Cython 0.25

**Comment by Zen-CODE** [comment]
Okay, I'm going to close this as cython versions are quite well documented, both in the Kivy and Buildozer docs, which specify exact versions of Cython. It's impossible to test or ensure compatibility with all. Please post again if you disagree.

Thanks

**Comment by lostc4t** [comment]
Does not work with Cython 0.25 or 0.25.2 for me.  I have the same issue.

**Comment by saccode** [comment]
Hi, Cython 0.25 doesnt work, i had 26 but downgraded to 0.25 and no luck. even tried with 0.21 with no luck. Cython complie error is the message i get.. Please help

**Comment by saccode** [comment]
Error message below..

Error compiling Cython file:
------------------------------------------------------------
...
        int resizable, int fullscreen, int border, int above, int CWOR, char *title)
cdef extern void x11_gl_swap()
cdef extern void x11_set_title(char *title)
cdef extern int x11_idle()
cdef extern Display *x11_get_display()
cdef extern Window x11_get_window()
           ^
------------------------------------------------------------

kivy/core/window/window_x11.pyx:70:12: 'Window' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
        self.system_size = size
        super(WindowX11, self).create_window()
        self._unbind_create_window()

    def get_window_info(self):
        cdef WindowInfoX11 window_info = WindowInfoX11()
            ^
------------------------------------------------------------

kivy/core/window/window_x11.pyx:221:13: 'WindowInfoX11' is not a type identifier


  STDERR:

**Comment by Neustart** [comment]
@saccode the same issue...

**Comment by Zen-CODE** [comment]
Okay, this is getting a bit long with too many uncertain comments (that  don't confirm versions etc). If you can't build, please create a new post confirming:
1. The exact version of cython you are using, and if you've tested with 0.25.2 for older versions, 0.27.3 for latest master/1.10.0).
2. The exact version of kivy (master or dev).
3. The full error log.
