### ISSUE TITLE
Python3 >= 3.11 compatibility

### ISSUE THREAD

**Issue by blackPantherOS** [kivy/buildozer#1571]
```
[DEBUG]:        jnius/jnius.c:34:10: fatal error: 'internal/pycore_frame.h' file not found
[DEBUG]:        #include "internal/pycore_frame.h"
[DEBUG]:                 ^~~~~~~~~~~~~~~~~~~~~~~~~
[DEBUG]:        1 error generated.
[DEBUG]:        error: command '/usr/bin/ccache' failed with exit code 1
Exception in thread background thread for pid 756831:
Traceback (most recent call last):
  File "/usr/lib64/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.11/site-packages/sh.py", line 1641, in wrap
    fn(*rgs, **kwargs)
  File "/usr/lib/python3.11/site-packages/sh.py", line 2569, in background_thread
    handle_exit_code(exit_code)
  File "/usr/lib/python3.11/site-packages/sh.py", line 2269, in fn
    return self.command.handle_command_exit_code(exit_code)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/sh.py", line 869, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /home/build/Projects/python3-qt5/Kivy/first_app/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/native-build/python3 setup.py build_ext -v

  STDOUT:
warning: [options] bootstrap class path not set in conjunction with -source 7
1 warning
running build_ext
building 'jnius' extension
/usr/bin/ccache /home/build/.buildozer/android/platform/android-ndk-r25b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -target aarch64-linux-android21 -fomit-frame-pointer -march=armv8-a -fPIC -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -target aarch64-linux-android21 -fomit-frame-pointer -march=armv8-a -fPIC -I/home/build/Projects/python3-qt5/Kivy/first_app/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/python3/arm64-v8a__ndk_target_21/python3/Include -DANDROID -I/home/build/.buildozer/android/platform/android-ndk-r25b/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include -I/home/build/Projects/python3-qt5/Kivy/first_app/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/tvfoci/arm64-v8a/include/python3.9 -fPIC -I/home/build/Projects/python3-qt5/Kivy/first_app/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/Include -I/home/build/Projects/python3-qt5/Kivy/first_app/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/native-build -c jnius/jnius.c -o build/temp.linux-x86_64-3.9/jnius/jnius.o
jnius/jnius.c:34:10: fatal error: 'internal/pycore_frame.h' file not found
#include "internal/pycore_frame.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
error: command '/usr/bin/ccache' failed with exit code 1

```

### Versions

* Python: 3.11 or greater
* OS: Any distro with python3 > 3.11
* Buildozer: 1.5.0

### Description

Build failed when system python is 3.11
because `pycore_frame.h` does not exists in previous versions

### buildozer.spec
Command:
```sh
buildozer android debug
```

Spec file:
```
not relevant, because working fine with python3 <= 3.9 versions
```

Workaround: 
```
cd where_your_project_storage
touch ./.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/Include/pycore_frame.h

```

**Comment by misl6** [comment]
Hi @blackPantherOS !

Can you please share your `buildozer.spec` file?

**Comment by Julian-O** [comment]
No response for 8 months. Closing as Can't Repro.

If you *can* provide a buildozer.spec and full log of this message, please let us know.
